[package]
name = "wormhole-anchor-sdk"
version = "0.1.0"
edition = "2021"
description = "SDK using Anchor interfaces to interact with Wormhole Solana Programs"

[dependencies]
anchor-lang = { version = "0.25.0", features = ["derive"] }
borsh = { version = "^0.9", optional = true }
solana-program = "~1.10.29"