[features]
seeds = false
skip-lint = false

[programs.localnet]
### WARNING: Be sure to change these pubkeys to reflect your deployed keypairs
hello_world = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
hello_token = "GDch61JmJpTo9npwenypnk3KdofmozK1hNaTdbYRkNPb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ts/tests/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./dependencies/spl_token_metadata.so"

### NOTE: Check against testing.env
[[test.genesis]]
address = "Bridge1p5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o"
program = "./dependencies/wormhole.so"

### NOTE: Check against testing.env
[[test.genesis]]
address = "B6RHG3mfcckmrYN1UhmJzyS1XX3fZKbkeUcpJe9Sy3FE"
program = "./dependencies/token_bridge.so"
### NOTE: Check against testing.env
